import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  analytics,
  footer,
}: Readonly<{
  children: React.ReactNode;
  analytics: React.ReactNode;
  footer: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <title>My Next.js App</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>
    <body>
    {analytics}
    <nav>Navigation Bar</nav>
    {children}
    {footer}
    </body>
    </html>
  );
}
